# Generated by Django 4.2.7 on 2023-11-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articulo_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='usuario',
        ),
    ]
